{% set name = "b3denv" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/b3denv-{{ version }}.tar.gz
  sha256: 536d627ef26681c1393abc41101fdf917e029c9a0e1138102c8b27bf0398401e

build:
  entry_points:
    - b3denv = b3denv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.0
    - pip
  run:
    - python >=2.0

test:
  imports:
    - b3denv
  commands:
    - pip check
    - b3denv --help
  requires:
    - pip

about:
  home: https://github.com/stenson/b3denv
  summary: Helpers for blender command-line use 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
