{% set name = "b3denv" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/b3denv-{{ version }}.tar.gz
  sha256: ab453cfc14ffac969158aa8dd33c62c995b5882b4c0abb87de70400c2b9ca345

build:
  entry_points:
    - b3denv = b3denv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - b3denv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stenson/b3denv
  summary: Helpers for blender command-line use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
