{% set name = "b3denv" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/b3denv-{{ version }}.tar.gz
  sha256: 6075423d5787901028bafae682d5bc37719ce44c675642f64a8b05f2fb3f887a

build:
  entry_points:
    - b3denv = b3denv:main
    - bdv = b3denv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - b3denv
  commands:
    - pip check
    - b3denv --help
    - bdv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stenson/b3denv
  summary: Helpers for blender command-line use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
