{% set name = "b3denv" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/b3denv-{{ version }}.tar.gz
  sha256: 84de0c78bbd85398f00975a988ae7d46238f78aab92e1966c5e5fe640aaccf8f

build:
  entry_points:
    - b3denv = b3denv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.0
    - pip
  run:
    - python >=2.0

test:
  imports:
    - b3denv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stenson/b3denv
  summary: Helpers for blender command-line use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
