{% set name = "b3denv" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/b3denv-{{ version }}.tar.gz
  sha256: 2c789d57e76d32b5d5eab0f65507e2edb55bbd3daad6126c18103a220109d4d1

build:
  entry_points:
    - b3denv = b3denv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - b3denv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stenson/b3denv
  summary: Helpers for blender command-line use
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
