schema_version: 1

context:
  name: b3denv
  version: "0.0.22"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/b3denv-${{ version }}.tar.gz
  sha256: bd5e40150a92526ee2d8e3080bfc8aab089c9ffda05c0fd4e65c0fc010bebd4b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - b3denv = b3denv:main
      - bdv = b3denv:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - b3denv
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - b3denv --version
      - bdv --version

about:
  summary: Helpers for blender command-line use
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/stenson/b3denv

extra:
  recipe-maintainers:
    - thewchan
